// Generated by scripts/build-fixtures.mjs — do not edit by hand.
// Real EXIF, real band means, real thumbhashes from the six JPEGs in
// public/photos. Regenerate with `npm run fixtures`.
//
// This is the shape phase 8 will read out of Convex (§11.1): every field here
// exists on the `photos` table. Captions and alt text are authored in
// src/fixtures/albums.ts, which is the part a studio would own.

export type Analysis = {
  /** Basename, sans extension — derivatives are `<base>@<w>.<ext>`. */
  base: string;
  file: string;
  /** Widths actually generated. Never upscaled past the intrinsic width. */
  widths: number[];
  width: number;
  height: number;
  thumbhash: string;
  palette: {
    /** Mean colour of the top 15%, in OKLCh. Tints the top blur field. */
    topBand: string;
    /** Mean colour of the bottom 20%. Tints the bottom blur field. */
    bottomBand: string;
    /** Hue only — chroma is clamped at the use site to ≤ 0.012 (§3.1). */
    shadowHue: number;
    /** Drives appearance switching at the §6.2 threshold. */
    meanL: number;
  };
  exif: {
    camera?: string;
    lens?: string;
    focal?: number;
    aperture?: number;
    shutter?: string;
    iso?: number;
    takenAt?: number;
  };
};

export const analyses = [
  {
    "file": "0AC1BB00-8C93-4F82-9C83-33436BC20098_1_105_c.jpeg",
    "base": "0AC1BB00-8C93-4F82-9C83-33436BC20098_1_105_c",
    "widths": [
      640,
      960,
      1024
    ],
    "width": 1024,
    "height": 768,
    "thumbhash": "URgKHYRyd3hfd4iTeCiJeHaCYDcI",
    "palette": {
      "topBand": "oklch(0.379 0.035 260)",
      "bottomBand": "oklch(0.281 0.029 72)",
      "shadowHue": 57,
      "meanL": 0.391
    },
    "exif": {
      "camera": "iPhone 11 Pro",
      "lens": "iPhone 11 Pro back camera",
      "focal": 6,
      "aperture": 2,
      "shutter": "1/20",
      "iso": 400,
      "takenAt": 1738432235000
    }
  },
  {
    "file": "7A415A50-CA9E-4FCD-939C-C288399514AD_1_105_c.jpeg",
    "base": "7A415A50-CA9E-4FCD-939C-C288399514AD_1_105_c",
    "widths": [
      640,
      960,
      1024
    ],
    "width": 1024,
    "height": 768,
    "thumbhash": "3EgOLYhXd4dvd4iRiId4hmdlgFcF",
    "palette": {
      "topBand": "oklch(0.565 0.028 322)",
      "bottomBand": "oklch(0.154 0.021 28)",
      "shadowHue": 33,
      "meanL": 0.535
    },
    "exif": {
      "camera": "iPhone 11 Pro",
      "lens": "iPhone 11 Pro back camera",
      "focal": 6,
      "aperture": 2,
      "shutter": "1/122",
      "iso": 125,
      "takenAt": 1755321841000
    }
  },
  {
    "file": "8C7ADF19-6C90-49C8-B0CD-FB07C1163C0F_1_105_c.jpeg",
    "base": "8C7ADF19-6C90-49C8-B0CD-FB07C1163C0F_1_105_c",
    "widths": [
      640,
      960,
      1024
    ],
    "width": 1024,
    "height": 768,
    "thumbhash": "HOgVJYKGiIh/d4iEd3eHeHeAevgG",
    "palette": {
      "topBand": "oklch(0.688 0.019 253)",
      "bottomBand": "oklch(0.295 0.077 128)",
      "shadowHue": 145,
      "meanL": 0.562
    },
    "exif": {
      "camera": "iPhone 11 Pro",
      "lens": "iPhone 11 Pro back camera",
      "focal": 6,
      "aperture": 2,
      "shutter": "1/2817",
      "iso": 25,
      "takenAt": 1751726577000
    }
  },
  {
    "file": "AD0590D4-82B3-43B3-ADED-564AC1E2DA56_1_105_c.jpeg",
    "base": "AD0590D4-82B3-43B3-ADED-564AC1E2DA56_1_105_c",
    "widths": [
      640,
      960,
      1024
    ],
    "width": 1024,
    "height": 768,
    "thumbhash": "WOcRJYZ3d3d/d4d0eEh4iHdgggcn",
    "palette": {
      "topBand": "oklch(0.556 0.1 249)",
      "bottomBand": "oklch(0.239 0.011 296)",
      "shadowHue": 261,
      "meanL": 0.479
    },
    "exif": {
      "camera": "iPhone 15 Pro Max",
      "lens": "iPhone 15 Pro Max back camera",
      "focal": 7,
      "aperture": 1.78,
      "shutter": "1/50",
      "iso": 800,
      "takenAt": 1783801401000
    }
  },
  {
    "file": "E751B9B9-54AA-4A27-883C-40FB02777A0A_1_105_c.jpeg",
    "base": "E751B9B9-54AA-4A27-883C-40FB02777A0A_1_105_c",
    "widths": [
      640,
      768
    ],
    "width": 768,
    "height": 1024,
    "thumbhash": "DggKFQKGhn+IB3hYeIp4d3eBcAgY",
    "palette": {
      "topBand": "oklch(0.341 0.021 278)",
      "bottomBand": "oklch(0.1 0.019 360)",
      "shadowHue": 11,
      "meanL": 0.328
    },
    "exif": {
      "camera": "iPhone 11 Pro",
      "lens": "iPhone 11 Pro back camera",
      "focal": 6,
      "aperture": 2,
      "shutter": "1/23",
      "iso": 500,
      "takenAt": 1738432054000
    }
  },
  {
    "file": "FEA65A2C-108D-4AFC-A148-2AD38E2EDDC2_1_105_c.jpeg",
    "base": "FEA65A2C-108D-4AFC-A148-2AD38E2EDDC2_1_105_c",
    "widths": [
      640,
      960,
      1024
    ],
    "width": 1024,
    "height": 768,
    "thumbhash": "y/cFFYI0hniPeHeFiYeIinmAtQcX",
    "palette": {
      "topBand": "oklch(0.339 0.032 250)",
      "bottomBand": "oklch(0.217 0.012 129)",
      "shadowHue": 227,
      "meanL": 0.286
    },
    "exif": {
      "camera": "iPhone 17",
      "lens": "iPhone 17 back camera",
      "focal": 6,
      "aperture": 1.6,
      "shutter": "1\"",
      "iso": 32,
      "takenAt": 1777751020000
    }
  }
] as const satisfies readonly Analysis[];
