/**
 * Self-hosts Interlude's dynamic subsets under a stable public URL.
 *
 * Why not `interlude-ui/font` (the Next font module)? It points at the full
 * `InterludeVariable.woff2`, which is 11MB — every Latin reader would pay for
 * 11,172 hangul syllables plus the CJK ideograph planes (§3.2 says explicitly
 * not to). The dynamic-subset set is 189 files behind `unicode-range`, so a
 * browser fetches only the ~138KB base subset unless the page actually renders
 * CJK.
 *
 * Why not `@import "interlude-ui/tailwind"` straight from node_modules? The
 * bundler would content-hash the woff2 URLs, and we could then no longer
 * `<link rel="preload">` the base subset — §3.2 wants the Latin face preloaded.
 * Copying to a stable path gives us both.
 *
 * Output (both gitignored, regenerated by predev/prebuild):
 *   public/fonts/interlude/*.woff2
 *   src/app/interlude.css
 */
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

// `interlude-ui` restricts its `exports`, so resolve through a subpath it does
// export and walk back up to the package root.
const pkg = path.resolve(
  path.dirname(new URL(import.meta.resolve("interlude-ui/css")).pathname),
  "../..",
);
const src = path.join(pkg, "dist/dynamic-subset");
const outFonts = path.resolve("public/fonts/interlude");
const outCss = path.resolve("src/app/interlude.css");

await mkdir(outFonts, { recursive: true });
await mkdir(path.dirname(outCss), { recursive: true });
await cp(src, outFonts, {
  recursive: true,
  filter: (f) => !f.endsWith(".css"),
});

const css = await readFile(
  path.join(src, "interlude-variable-dynamic-subset.css"),
  "utf8",
);

const header = `/* Generated by scripts/sync-fonts.mjs — do not edit.
   Interlude, SIL Open Font License 1.1. https://avanturation.com/interlude */\n`;

await writeFile(
  outCss,
  header + css.replaceAll("url('./", "url('/fonts/interlude/"),
  "utf8",
);

console.log(`interlude: subsets → public/fonts/interlude, css → src/app/interlude.css`);
